### ISSUE TITLE
Track/Render Total GHG Emissions Over Time

### ISSUE THREAD

**Issue by vkoves** [vkoves/electrify-chicago#102]
We're tracking electricity use, gas use, and GHG intensity, but not total emissions. We should make sure to track and/or render that data (maybe we are tracking it and I forgot to render it):

Here's an example from [Merch Mart](https://electrifychicago.net/building/merchandise-mart/):

![Screenshot from 2024-05-15 14-53-04](https://github.com/vkoves/electrify-chicago/assets/3187531/ab7a5b63-aeb5-48b8-841a-a80a83d7b31b)

**Comment by alexkcode** [comment]
Some of the emissions look like they're off by a digit or two (ex: United Center, Crown Hall, but seems like it's probably a data quality/script issue or some other external problem.
