### ISSUE TITLE
Report Data Integrity Issues with City Benchmarking Data

### ISSUE THREAD

**Issue by derekeder** [vkoves/electrify-chicago#115]
Data source: https://data.cityofchicago.org/Environment-Sustainable-Development/Chicago-Energy-Benchmarking/xq83-jr8c/about_data

- buildings marked with 0 for natural gas usage
- missing energy star scores
- missing Chicago Energy Scores
- discrepancies with large swings in usage (Crown Hall 10x district steam use between 2020 and 2021)

**Comment by vkoves** [comment]
I've had some back-and-forth with the city about those issues and buildings having gas and electricity use reported and no emissions, and they are looking at tweaking the reporting requirements and ensuring buildings have more complete data. But on the accuracy front, they've said it's not their responsibility and that there's no way to ensure the data is accurate 🫠 

With all that said, closing - the city was made aware of the data issues.
