### ISSUE TITLE
Update References to "Natural Gas" to "Gas" or "Methane Gas"

### ISSUE THREAD

**Issue by vkoves** [vkoves/electrify-chicago#124]
Natural Gas is a marketing and not technical term, so we should update it to something a little more accurate. Let's change it to "Fossil Gas".

**Comment by vkoves** [comment]
This will be assigned to Sean (@burningchicago)

**Comment by sburnschicago** [comment]
Was able to get started with Docker and build website locally.
Will search code for all instances of Natural Gas, make changes, verify changes go through to website.
Some concern about where NaturalGas is used as a variable as opposed to a UI element, so that is why we test.

**Comment by sburnschicago** [comment]
More complicated than I thought it was. Still working on it.
