### ISSUE TITLE
Add "Email This Building Button" To Building Details

### ISSUE THREAD

**Issue by vkoves** [vkoves/electrify-chicago#126]
We don't have the contact info for buildings, but we should create a modal that gives user's a filled out template email with the building's name and maybe some stats. Here's a V1 mockup from [my Figma](https://www.figma.com/design/rJQiz1waySWCRN9NdGtjtg/Electrify-Chicago?node-id=303-65&node-type=FRAME&t=zjpLfNePSroNp6yw-0)

![Email Modal](https://github.com/user-attachments/assets/954842f0-23d6-424c-8fe1-17a4d9f52f20)

**Make sure to think about accessibility, esp. trapping focus in the modal**, and see the [<dialog> element (MDN)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog)

**Comment by vkoves** [comment]
@vaidehia - here's the icons you need (they are white, but they exist I swear 😆 )

[Email icon](https://github.com/user-attachments/assets/7a3fd7ad-b3d6-43cd-a493-b9fc9f4c1c44) | [Copy icon](https://github.com/user-attachments/assets/45a174db-db63-4a15-855f-f46be85ebb52)

**Comment by RobertIsmo** [comment]
We @sanjay872 and @wangbertha
