### ISSUE TITLE
Split out Take Action Tips Into Its Own Page

### ISSUE THREAD

**Issue by vkoves** [vkoves/electrify-chicago#127]
There's a lot of info in the take action page, so we should **split this into a new page** and add a link instead, like "Own This Building? Take Action"

<img width="670" alt="Screenshot_126" src="https://github.com/user-attachments/assets/96230e3c-6f67-4cc3-a36b-af70404d9f5c">

**Comment by vkoves** [comment]
Charles Bergman volunteered to take this on! (@drbaryon)

**Comment by brayckner** [comment]
Taking this @vkoves
