### ISSUE TITLE
There are weird fractions for certain info boxes

### ISSUE THREAD

**Issue by SuragNuthulapaty** [vkoves/electrify-chicago#39]
When natural gas and electricty use are zero, the fractions for medians say 1/infinity. It should probably be changed to not show up.

![image](https://github.com/vkoves/electrify-chicago/assets/77648585/a597e3fb-3fdf-45e1-bb65-9ab55b2b633e)

**Comment by vkoves** [comment]
@SuragNuthulapaty - what URL was this, as in what building?

**Comment by SuragNuthulapaty** [comment]
it was [http://localhost:8080/building/4631/](url)

**Comment by vkoves** [comment]
@SuragNuthulapaty - do you have a prod URL? Are you sure this isn't a bug on your branch?

**Comment by SuragNuthulapaty** [comment]
@vkoves This is only on my branch because it is a part of the new data I just added

**Comment by vkoves** [comment]
Ah, then I think you should list it on that PR and we should fix it before it gets merged - this isn't an issue with the repo, it's an issue with the PR (if that makes sense). Going to close this.
