### ISSUE TITLE
Add Graph For Emissions Over Time On Building Details (Requires Integrating Full Data Source)

### ISSUE THREAD

**Issue by vkoves** [vkoves/electrify-chicago#4]
**Blocked by issue #73**, which will integrate the full data source.

Buildings like Keating may still be very high emitters, but they also have had emissions (and natural gas use) decrease over time, so to give a full picture it would be good to integrate historical data into a line graph showing the emissions over time.

This would also make it so that if we get, say, 2021 emissions data the old data would still be available and you could see the change YoY.

Since we have lots of fields you might want to see over time, we'd probably want to make the graph interactive, letting the user travel between different visualizations, but defaulting to a really useful one, like GHG intensity.

**Comment by alexkcode** [comment]
As I understand `ChicagoEnergyBenchmarking.csv` seems to be the best data source for this, but that means we might have to repeat all the transformations in the Python scripts.

**Comment by vkoves** [comment]
Yeah let's tackle tests first via #41 to ensure stability
