### ISSUE TITLE
United Center (& Likely Other Buildings) Show in Search But Have No Stats

### ISSUE THREAD

**Issue by vkoves** [vkoves/electrify-chicago#53]
![image](https://github.com/vkoves/electrify-chicago/assets/3187531/c3d26a40-900c-4aa6-9ce2-45471d86dd82)

**Comment by vkoves** [comment]
Looking at a [data portal search for United Center](https://data.cityofchicago.org/Environment-Sustainable-Development/Chicago-Energy-Benchmarking/xq83-jr8c/explore/query/SELECT%0A%20%20%60data_year%60%2C%0A%20%20%60id%60%2C%0A%20%20%60property_name%60%2C%0A%20%20%60reporting_status%60%2C%0A%20%20%60address%60%2C%0A%20%20%60zip_code%60%2C%0A%20%20%60chicago_energy_rating%60%2C%0A%20%20%60exempt_from_chicago_energy_rating%60%2C%0A%20%20%60community_area%60%2C%0A%20%20%60primary_property_type%60%2C%0A%20%20%60gross_floor_area_buildings_sq_ft%60%2C%0A%20%20%60year_built%60%2C%0A%20%20%60of_buildings%60%2C%0A%20%20%60water_use_kgal%60%2C%0A%20%20%60energy_star_score%60%2C%0A%20%20%60electricity_use_kbtu%60%2C%0A%20%20%60natural_gas_use_kbtu%60%2C%0A%20%20%60district_steam_use_kbtu%60%2C%0A%20%20%60district_chilled_water_use_kbtu%60%2C%0A%20%20%60all_other_fuel_use_kbtu%60%2C%0A%20%20%60site_eui_kbtu_sq_ft%60%2C%0A%20%20%60source_eui_kbtu_sq_ft%60%2C%0A%20%20%60weather_normalized_site_eui_kbtu_sq_ft%60%2C%0A%20%20%60weather_normalized_source_eui_kbtu_sq_ft%60%2C%0A%20%20%60total_ghg_emissions_metric_tons_co2e%60%2C%0A%20%20%60ghg_intensity_kg_co2e_sq_ft%60%2C%0A%20%20%60latitude%60%2C%0A%20%20%60longitude%60%2C%0A%20%20%60location%60%2C%0A%20%20%60row_id%60%2C%0A%20%20%60%3A%40computed_region_43wa_7qmu%60%2C%0A%20%20%60%3A%40computed_region_vrxf_vc4k%60%2C%0A%20%20%60%3A%40computed_region_6mkv_f3dw%60%2C%0A%20%20%60%3A%40computed_region_bdys_3d7i%60%2C%0A%20%20%60%3A%40computed_region_awaf_s7ux%60%0ASEARCH%20%22united%20center%22/page/filter) it looks like the United Center **did** submit in 2019, and has data, so I don't know why this isn't rendering.

**Comment by alexkcode** [comment]
United Center 2019 data confirmed to be produced in `building-benchmarks.csv` file produce by `process-data.py` as well.

**Comment by vkoves** [comment]
It looks like the issue is related to the fact that the front-end wants to pull in property stats (e.g. Avg. Electricity Use for Indoor Arenas) but the stats don't exist for older buildings:

![Screenshot from 2023-09-26 21-23-35](https://github.com/vkoves/electrify-chicago/assets/3187531/6528d0b2-a1bc-4306-b79e-2afa2b603ada)
![Screenshot from 2023-09-26 21-23-32](https://github.com/vkoves/electrify-chicago/assets/3187531/6b1c2a55-6b48-4961-bca5-119a9e8196e1)

The fix is that **if we're showing archival data (not the current year) we should not try to render property type stats**. Even if the property type still exists, the stats are all for the latest year (2021) and so wouldn't be useful.
