### ISSUE TITLE
Add Mobile Menu to Cleanup Header

### ISSUE THREAD

**Issue by vkoves** [vkoves/electrify-chicago#7]
On mobile, the header is getting increasingly cluttered: 

<img src="https://user-images.githubusercontent.com/3187531/228134799-31bbd3d0-1623-458a-adb8-9c3e7fa9248b.png" width="400">

We should add a hamburger style mobile menu and make it so that you don't see all those options by default.

**Comment by GrandSuccess87** [comment]
Hello! I came across this project and would certainly like to volunteer to help 😀 Happy to work on this ticket!

**Comment by vkoves** [comment]
@GrandSuccess87 - we'd love that! I think a basic mobile menu that's a vertical list would be perfect, but there are some accessibility things to consider that might require some back and forth. If you'd like to get started on it, [this article](https://www.a11ymatters.com/pattern/mobile-nav/) is great, and this icon from Icomoon should work perfectly!

<img src="https://github.com/user-attachments/assets/99e0b88d-6106-49cb-9349-ed4157373944" width="200">

**Comment by GrandSuccess87** [comment]
Wonderful! Thanks for forwarding the article, looking forward to working on this!
