### ISSUE TITLE
Add City Retrofit Reports

### ISSUE THREAD

**Issue by vkoves** [vkoves/electrify-chicago#70]
Some buildings have public data available on their retrofits, like The Rookery here: https://www.chicago.gov/content/dam/city/sites/retrofit-chicago-2/pastparticipants/The%20Rookery.pdf ([Electrify Chicago on Rookery](https://electrifychicago.net/building/the-rookery-building/))

View all case studies here: https://www.chicago.gov/city/en/sites/retrofit-chicago2/home/participant-achievments/past-participants.html#case-studies

**Comment by vkoves** [comment]
Relates to #123

**Comment by vaidehia** [comment]
Hi! Victor, I'll be starting work on this Issue. -Vaidehi

**Comment by vkoves** [comment]
Resolved in #133
