### ISSUE TITLE
Integrate Full Data Source (Historic Data)

### ISSUE THREAD

**Issue by alexkcode** [vkoves/electrify-chicago#73]
Depends on #89.

Currently we are only feeding the "latest year" (the last year of data that we have, not necessarily the current year) to the frontend of the website. We should track the below fields over time so that we can build further data visualizations (e.g. issue #4).

Fields to track over time:

-  Submission Status (so we know if they skipped a year?)
-  Square Footage
-  TotalGHGEmissions
-  GHGIntensity
-  SiteEUI
-  SourceEUI
-  ENERGYSTARScore
-  ElectricityUse
-  NaturalGasUse
-  DistrictSteamUse
-  DistrictChilledWaterUse

The main script for this change should be `src/data/scripts/clean_and_pare_down_data_current_year.py`. The current thinking is we either modify that component to do what we want or, more ideally, we create a new script that outputs to a different file to maintain the stability of current processes.

**This should output to a separate CSV file in the dist** (e.g. `buildings_across_years.csv`) so that building list pages and search pages don't need to do a bunch of complex filtering. Also the current ranking UI might break. We'd basically have a _latest_ data set (what we have right now) and the historical data we can query building by building.

**Comment by thetenzinwoser** [comment]
I'm working on the visualization of this data!

**Comment by vkoves** [comment]
@thetenzinwoser - awesome! Here's all the [info on Merch Mart](https://data.cityofchicago.org/Environment-Sustainable-Development/Chicago-Energy-Benchmarking/xq83-jr8c/explore/query/SELECT%0A%20%20%60data_year%60%2C%0A%20%20%60id%60%2C%0A%20%20%60property_name%60%2C%0A%20%20%60reporting_status%60%2C%0A%20%20%60address%60%2C%0A%20%20%60zip_code%60%2C%0A%20%20%60chicago_energy_rating%60%2C%0A%20%20%60exempt_from_chicago_energy_rating%60%2C%0A%20%20%60community_area%60%2C%0A%20%20%60primary_property_type%60%2C%0A%20%20%60gross_floor_area_buildings_sq_ft%60%2C%0A%20%20%60year_built%60%2C%0A%20%20%60of_buildings%60%2C%0A%20%20%60water_use_kgal%60%2C%0A%20%20%60energy_star_score%60%2C%0A%20%20%60electricity_use_kbtu%60%2C%0A%20%20%60natural_gas_use_kbtu%60%2C%0A%20%20%60district_steam_use_kbtu%60%2C%0A%20%20%60district_chilled_water_use_kbtu%60%2C%0A%20%20%60all_other_fuel_use_kbtu%60%2C%0A%20%20%60site_eui_kbtu_sq_ft%60%2C%0A%20%20%60source_eui_kbtu_sq_ft%60%2C%0A%20%20%60weather_normalized_site_eui_kbtu_sq_ft%60%2C%0A%20%20%60weather_normalized_source_eui_kbtu_sq_ft%60%2C%0A%20%20%60total_ghg_emissions_metric_tons_co2e%60%2C%0A%20%20%60ghg_intensity_kg_co2e_sq_ft%60%2C%0A%20%20%60latitude%60%2C%0A%20%20%60longitude%60%2C%0A%20%20%60location%60%2C%0A%20%20%60row_id%60%2C%0A%20%20%60%3A%40computed_region_43wa_7qmu%60%2C%0A%20%20%60%3A%40computed_region_vrxf_vc4k%60%2C%0A%20%20%60%3A%40computed_region_6mkv_f3dw%60%2C%0A%20%20%60%3A%40computed_region_bdys_3d7i%60%2C%0A%20%20%60%3A%40computed_region_awaf_s7ux%60%0AWHERE%20%60id%60%20IN%20%28%22103656%22%29%0AORDER%20BY%20%60data_year%60%20ASC%20NULL%20LAST/page/filter) over the years, it's improved every year, which I think is a great thing to highlight.

**Comment by vkoves** [comment]
@alexkcode - have you started on this issue? I _think_ you have and had some code going, but I wanted to check just in case
