### ISSUE TITLE
Calculate Potential Fines Based on Number of Non-Submitting Buildings

### ISSUE THREAD

**Issue by alexkcode** [vkoves/electrify-chicago#75]
Calculate the total amount of potential fines based on the number of non-compliant buildings in the data according to this ordinance: https://www.chicago.gov/content/dam/city/progs/env/EnergyBenchmark/SO2017-7060.pdf

1. Get latest Environment Sustainable dataset from the Chicago Data Portal [here](https://data.cityofchicago.org/Environment-Sustainable-Development/Chicago-Energy-Benchmarking/xq83-jr8c/explore/query/SELECT%0A%20%20%60data_year%60%2C%0A%20%20%60id%60%2C%0A%20%20%60property_name%60%2C%0A%20%20%60reporting_status%60%2C%0A%20%20%60address%60%2C%0A%20%20%60zip_code%60%2C%0A%20%20%60chicago_energy_rating%60%2C%0A%20%20%60exempt_from_chicago_energy_rating%60%2C%0A%20%20%60community_area%60%2C%0A%20%20%60primary_property_type%60%2C%0A%20%20%60gross_floor_area_buildings_sq_ft%60%2C%0A%20%20%60year_built%60%2C%0A%20%20%60of_buildings%60%2C%0A%20%20%60water_use_kgal%60%2C%0A%20%20%60energy_star_score%60%2C%0A%20%20%60electricity_use_kbtu%60%2C%0A%20%20%60natural_gas_use_kbtu%60%2C%0A%20%20%60district_steam_use_kbtu%60%2C%0A%20%20%60district_chilled_water_use_kbtu%60%2C%0A%20%20%60all_other_fuel_use_kbtu%60%2C%0A%20%20%60site_eui_kbtu_sq_ft%60%2C%0A%20%20%60source_eui_kbtu_sq_ft%60%2C%0A%20%20%60weather_normalized_site_eui_kbtu_sq_ft%60%2C%0A%20%20%60weather_normalized_source_eui_kbtu_sq_ft%60%2C%0A%20%20%60total_ghg_emissions_metric_tons_co2e%60%2C%0A%20%20%60ghg_intensity_kg_co2e_sq_ft%60%2C%0A%20%20%60latitude%60%2C%0A%20%20%60longitude%60%2C%0A%20%20%60location%60%2C%0A%20%20%60row_id%60%2C%0A%20%20%60%3A%40computed_region_43wa_7qmu%60%2C%0A%20%20%60%3A%40computed_region_vrxf_vc4k%60%2C%0A%20%20%60%3A%40computed_region_6mkv_f3dw%60%2C%0A%20%20%60%3A%40computed_region_bdys_3d7i%60%2C%0A%20%20%60%3A%40computed_region_awaf_s7ux%60%0AWHERE%0A%20%20%28%60data_year%60%20%3E%202018%29%0A%20%20AND%20caseless_one_of%28%60reporting_status%60%2C%20%22Not%20Submitted%22%29/page/filter). The export can be found here: 
[Chicago_Energy_Benchmarking_20240220_superset.csv](https://github.com/vkoves/electrify-chicago/files/14353461/Chicago_Energy_Benchmarking_20240220_superset.csv)
2. Find number of buildings not in compliance with city emission data requirements and their associated square footage.
3. Map buildings to fine levels based on building square footage.
4. Sum total fines based on those fines associated to the buildings 

Buildings that are non-compliant will show "Not Submitted" in the `Reporting Status` column of the data. The data in the link shown above should already be filtered.

**Comment by vkoves** [comment]
Since the data set (2019 - 2023 buildings that didn't submit) contains 2,905 buildings and the [latest notice](https://www.chicago.gov/content/dam/city/progs/env/EnergyBenchmark/sample_notification_letter.pdf) says a max fine is of $9,200, that's a total of $26,726,000 in potential fines ($26.7 million dollars!)

![Screenshot from 2024-02-20 20-58-35](https://github.com/vkoves/electrify-chicago/assets/3187531/1270c63e-113c-49be-8265-b3f8d5298a7b)

Here's a screenshot from the notice of the fines:

![Screenshot from 2024-02-20 21-01-58](https://github.com/vkoves/electrify-chicago/assets/3187531/00b8f18d-afbf-4733-ad6d-165f103e940b)

**Comment by alexkcode** [comment]
![image](https://github.com/vkoves/electrify-chicago/assets/7072135/15da84b1-f269-4cca-b389-98bc1d02be09)

If we use the minimum fine given from the notice ($100) we get the first number shown `$290,500`, if we use the maximum given the notice ($9,200) the total fines would be `$26,726,000`.
